### ISSUE TITLE
Static IP

### ISSUE THREAD

**Issue by topshelfjake** [JeDaYoshi/docker-nextdns#2]
Everyone,

Can a static IP be configured for the docker-compose image? When I deploy the image, it creates a new network and comes up on a completely (non-existent) network. I've been playing with the docker-compose syntax, but haven't been successful in figuring it out. Hoping you can help add this information as optional. 

Thanks,
Jake

**Comment by jeda** [comment]
Hey there!

Could you share the `docker-compose.yml` file you're trying to deploy this with?
Shouldn't be an issue, since it depends mainly on Docker - not doing anything weird that would not make it work.

**Comment by topshelfjake** [comment]
I really didn't do anything complicated with the configuration you provided. Maybe I'm just not understanding what I need to do to access the container for configuration. 


services:
  nextdns:
    container_name: nextdns
    image: jedayoshi/nextdns:latest
    restart: always
    ports:
      - 53:53/tcp
      - 53:53/udp
    environment:
      NEXTDNS_PROFILE: xxxxxx
      NEXTDNS_CACHE_SIZE: 10m
      NEXTDNS_REPORT_CLIENT_INFO: true
      NEXTDNS_USE_HOSTS: true
    volumes:
      - /docker/nextdns/hosts:/etc/hosts:ro

**Comment by jeda** [comment]
I don't see that you're defining a static IP in there.

Here's an example that should work fine:

```yaml
version: "3"

services:
  nextdns:
    container_name: nextdns
    image: jedayoshi/nextdns:latest
    restart: always
    networks:
      nextdns:
        ipv4_address: 10.53.53.2
    ports:
      - 53:53/tcp
      - 53:53/udp
    environment:
      NEXTDNS_PROFILE: xxxxxx
      NEXTDNS_CACHE_SIZE: 10m
      NEXTDNS_REPORT_CLIENT_INFO: true
      NEXTDNS_USE_HOSTS: true
    volumes:
      - /docker/nextdns/hosts:/etc/hosts:ro

networks:
  nextdns:
    name: nextdns
    ipam:
      config:
        - subnet: 10.53.53.0/30
```

The IP would be `10.53.53.2`. `10.53.53.1` is used by Docker for the interface.
