### ISSUE TITLE
How to have multiple profiles based on MAC

### ISSUE THREAD

**Issue by vavallee** [JeDaYoshi/docker-nextdns#3]
Hi!
Currently using the old bizkut docker image for NextDNS CLI, but having trouble with configs.

Am wondering if I can use this image and have several MAC addresses assigned a profile and then a default for the rest?

eg:  -listen :5352 -report-client-info -setup-router -log-queries -cache-size
        12MB -config 11:11:11:11:11=conf1 -config 22:22:22:22:22=conf1 -config 33:33:33:33:33=conf1 -config 14141

**Comment by jeda** [comment]
This is dependent on NextDNS client's support, not specific to the image.
Just define multiple clients in the environment variables and that should do the trick.
Also remember to use `network_mode: host` / `--net=host` so it can see the MAC addresses.

**Comment by vavallee** [comment]
Can you give an example? I am not sure how my above configs should look

**Comment by jeda** [comment]
An example using a `docker-compose.yml` file:

```yaml
version: "3"

services:
  nextdns:
    container_name: "nextdns"
    image: "jedayoshi/nextdns:latest"
    restart: "always"
    network_mode: "host"
    environment:
      # this is the default
      NEXTDNS_PROFILE: "xxxxxx"
      # define the split ones per device here, with a label to recognise them
      NEXTDNS_PROFILE_DEVICE1: "aa:aa:aa:aa:aa:aa=aaaaaa"
      NEXTDNS_PROFILE_DEVICE2: "ab:ab:ab:ab:ab:ab=bbbbbb"
      # etc.
      NEXTDNS_CACHE_SIZE: "10m"
      NEXTDNS_REPORT_CLIENT_INFO: "true"
```
