### ISSUE TITLE
flag provided but not defined: -svc-service-host

### ISSUE THREAD

**Issue by vavallee** [JeDaYoshi/docker-nextdns#4]
When I run the image, I get 

flag provided but not defined: -svc-service-host

That value was auto-populated with the internal IP of my kubernetes pod.

**Comment by jeda** [comment]
Likely because `NEXTDNS_SVC_SERVICE_HOST` is being defined as an environment variable, and the client is not going to recognise this. You need to make sure this is not passed to the container.

**Comment by vavallee** [comment]
ok. I tried defining that key and setting the value to "". But same results, here's the edited output.

`Running with arguments: -setup-router=true -profile=11111111 -svc-service-host= -svc-port-5353-udp-addr=10.43.89.130 -svc-port-5353-udp-port=5353 -svc-port-5353-udp-proto=udp -use-hosts=false -svc-port=udp://10.43.89.130:5353 -svc-service-port=5353 -svc-port-5353-udp=udp://10.43.89.130:5353 -cache-size=10m -report-client-info=true -profile=11:11:11:11:11=config1 -svc-service-port-nextdns=5353 -profile=22:22:22:22:=config1`

**Comment by jeda** [comment]
Setting the value to "" will not work, they should be undefined entirely. Same with `svc-port`, `svc-service-port` etc. And like I said in the other issue, NAT will bring issues if you want MAC addresses to work.

**Comment by vavallee** [comment]
ok, Since I am not defining these key/values, how can I remove them? My config is:

```
spec:
      containers:
      - env:
        - name: NEXTDNS_PROFILE
          value: "111111"
        - name: NEXTDNS_PROFILE_MYMAC
          value: 11:11:11:11:11=config1
        - name: NEXTDNS_PROFILE_ANOTHERMAC
          value: 22:22:22:22:22=config1
        - name: NEXTDNS_CACHE_SIZE
          value: 10m
        - name: NEXTDNS_REPORT_CLIENT_INFO
          value: "true"
```
